### PR TITLE
travis-ci: initial config

### PR DESCRIPTION
**Pull request by dpocock**

### CODE REVIEW

**Comment by sam-github** [comment]
LGTM

**Comment by sam-github** [comment]
"looks good to me, you merge"

**Comment by sam-github** [comment]
If the first commit doesn't work standalone (looks like it won't if its missing deps), you may wish to squash the two into a single working commit before merge.

**Comment by dpocock** [comment]
This now runs the ```make test``` with as much success as I experience running it from the command line so I've merged it.

**Comment by sam-github** [comment]
OK, thanks.

**Pull request merged**
